<?xml version="1.0" encoding="ISO-8859-1"?>

<!--**************************************************** -->
<!-- Copyright (c) 2004, 2005, 2006, 2007, 2008, 2009 Cisco Systems, Inc. -->
<!-- All rights reserved. -->
<!--**************************************************** -->


<!DOCTYPE IFMMDF [
<!ELEMENT IFMMDF (DEVICEGROUP*)>
<!ELEMENT DEVICEGROUP (DEVICEGROUP*,DEVICE*)>

<!ATTLIST DEVICEGROUP
        MDFID  CDATA #REQUIRED
        CISCOMDFID  CDATA #REQUIRED
        NAME  CDATA #REQUIRED
        ICON  CDATA #IMPLIED
        DESC  CDATA #IMPLIED>

<!ELEMENT DEVICE (SYSOID*)>
<!ATTLIST DEVICE
        MDFID  CDATA #REQUIRED
        CISCOMDFID  CDATA #REQUIRED
        NAME  CDATA #REQUIRED
        ICON  CDATA #IMPLIED
        DESC  CDATA #IMPLIED>

<!ELEMENT SYSOID EMPTY>

<!ATTLIST SYSOID
        OID CDATA #REQUIRED
        NAME CDATA #REQUIRED>
]>

<!-- version : 1.32 (001) Last Modified on mm-dd-yy:10-13-09 -->
<IFMMDF>

        <DEVICEGROUP NAME="Cisco UCS Series" MDFID="101010101"
                        CISCOMDFID="101010101">
                        <DEVICEGROUP NAME="Cisco UCS B-Series Servers" MDFID="101010102"
                                CISCOMDFID="101010102">
                                <DEVICE NAME="Cisco UCS 6120XP 20-Port Fabric Interconnect" MDFID="282579053" CISCOMDFID="282579053">
                                        <SYSOID OID="1.3.6.1.4.1.9.12.3.1.3.847" NAME="OID:1.3.6.1.4.1.9.12.3.1.3.847" />
                                </DEVICE>

                                <DEVICE NAME="Cisco UCS 6140XP 40-Port Fabric Interconnect" MDFID="282579064" CISCOMDFID="282579064" >
                                                                <SYSOID OID="1.3.6.1.4.1.9.12.3.1.3.899" NAME="OID:1.3.6.1.4.1.9.12.3.1.3.899" />
                                                </DEVICE>
                                <DEVICE NAME="Cisco UCS 6248UP 48-Port Fabric Interconnect" MDFID="283742224" CISCOMDFID="283742224"  >
                                                        <SYSOID OID="1.3.6.1.4.1.9.12.3.1.3.1062" NAME="OID:1.3.6.1.4.1.9.12.3.1.3.1062" />
                                </DEVICE>
                                <DEVICE NAME="Cisco UCS 6296UP 96-Port Fabric Interconnect" MDFID="284174470" CISCOMDFID="284174470"  >
                                                                <SYSOID OID="1.3.6.1.4.1.9.12.3.1.3.1063" NAME="OID:1.3.6.1.4.1.9.12.3.1.3.1063" />
                                </DEVICE>
                        </DEVICEGROUP>
                        <DEVICEGROUP NAME="Cisco UCS C-Series Servers" MDFID="101010103" CISCOMDFID="101010103">
                                <DEVICE NAME="Cisco UCS C240 M3 Rack Server" MDFID="284262049" CISCOMDFID="284262049">
                                        <SYSOID OID="1.3.6.1.4.1.9.1.1514" NAME="OID:1.3.6.1.4.1.9.1.1514" />
                                </DEVICE>
                        </DEVICEGROUP>
    </DEVICEGROUP>

        <DEVICEGROUP NAME="Universal Gateways and Access Servers"
                MDFID="268437594" CISCOMDFID="268437594" ICON="16x16_access_gateway_sf.gif">
                <!--<DEVICEGROUP NAME="Cisco 2500 Series Access Servers"
                        MDFID="268437595" CISCOMDFID="268437595" ICON="16x16-NAS_SF.gif">
                        <DEVICE NAME="Cisco 2509 Access Server" MDFID="268437596"
                                CISCOMDFID="268437596">
                                <SYSOID OID="1.3.6.1.4.1.9.1.153" NAME="OID:1.3.6.1.4.1.9.1.153" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 2510 Access Server" MDFID="268437597"
                                CISCOMDFID="268437597">
                                <SYSOID OID="1.3.6.1.4.1.9.1.26" NAME="OID:1.3.6.1.4.1.9.1.26" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 2511 Access Server" MDFID="268437598"
                                CISCOMDFID="268437598">
                                <SYSOID OID="1.3.6.1.4.1.9.1.154" NAME="OID:1.3.6.1.4.1.9.1.154" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 2512 Access Server" MDFID="268437599"
                                CISCOMDFID="268437599">
                                <SYSOID OID="1.3.6.1.4.1.9.1.28" NAME="OID:1.3.6.1.4.1.9.1.28" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco AS5200 Series Universal Access Servers"
                        MDFID="268437610" CISCOMDFID="268437610" ICON="16x16-NAS_SF.gif">
                        <DEVICE NAME="Cisco AS5201 Universal Access Server" MDFID="268437611"
                                CISCOMDFID="268437611">
                                <SYSOID OID="1.3.6.1.4.1.9.1.109" NAME="OID:1.3.6.1.4.1.9.1.109" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco AS5300 Series Universal Gateways"
                        MDFID="268437612" CISCOMDFID="268437612">
                        <DEVICE NAME="Cisco AS5350 Universal Gateway" MDFID="268437613"
                                CISCOMDFID="268437613">
                                <SYSOID OID="1.3.6.1.4.1.9.1.313" NAME="OID:1.3.6.1.4.1.9.1.313" />
                        </DEVICE>
                        <DEVICE NAME="Cisco AS5300 Access Server" MDFID="269065635"
                                CISCOMDFID="269065635">
                                <SYSOID OID="1.3.6.1.4.1.9.1.162" NAME="OID:1.3.6.1.4.1.9.1.162" />
                        </DEVICE>
                        <DEVICE NAME="Cisco AS5350XM Universal Gateway" MDFID="279677868"
                                CISCOMDFID="279677868">
                                <SYSOID OID="1.3.6.1.4.1.9.1.679" NAME="OID:1.3.6.1.4.1.9.1.679" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco AS5400 Series Universal Gateways"
                        MDFID="269065637" CISCOMDFID="269065637">
                        <DEVICE NAME="Cisco AS5400 Universal Gateway" MDFID="274068131"
                                CISCOMDFID="274068131">
                                <SYSOID OID="1.3.6.1.4.1.9.1.274" NAME="OID:1.3.6.1.4.1.9.1.274" />
                        </DEVICE>
                        <DEVICE NAME="Cisco AS5400XM Universal Gateway" MDFID="279677871"
                                CISCOMDFID="279677871">
                                <SYSOID OID="1.3.6.1.4.1.9.1.668" NAME="OID:1.3.6.1.4.1.9.1.668" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco AS5800 Series Universal Gateways"
                        MDFID="269065638" CISCOMDFID="269065638">
                        <DEVICE NAME="Cisco AS5800 Access Server" MDFID="268437615"
                                CISCOMDFID="268437615">
                                <SYSOID OID="1.3.6.1.4.1.9.1.188" NAME="OID:1.3.6.1.4.1.9.1.188" />
                        </DEVICE>
                        <DEVICE NAME="Cisco AS5850 Universal Gateway" MDFID="268437616"
                                CISCOMDFID="268437616">
                                <SYSOID OID="1.3.6.1.4.1.9.1.308" NAME="OID:1.3.6.1.4.1.9.1.308" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Other Access Devices" MDFID="999990940"
                        CISCOMDFID="999990940">
                        <DEVICE NAME="TerminalServer" MDFID="999990936" CISCOMDFID="999990936">
                                <SYSOID OID="1.3.6.1.4.1.9.1.2" NAME="OID:1.3.6.1.4.1.9.1.2" />
                        </DEVICE>
                </DEVICEGROUP>
        </DEVICEGROUP>
        <DEVICEGROUP NAME="Content Networking" MDFID="268437639"
                CISCOMDFID="268437639" ICON="16x16_content_distri_man_sf.gif">
                <DEVICEGROUP NAME="Cisco 500 Series Cache Engines" MDFID="268437652"
                        CISCOMDFID="268437652">
                        <DEVICE NAME="Cisco 500 Cache Engine" MDFID="999990101"
                                CISCOMDFID="999990101">
                                <SYSOID OID="1.3.6.1.4.1.9.1.240" NAME="OID:1.3.6.1.4.1.9.1.240" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.9" NAME="OID:1.3.6.1.4.1.9.1.9" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.244" NAME="OID:1.3.6.1.4.1.9.1.244" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco Micro Webservers" MDFID="268437677"
                        CISCOMDFID="268437677">
                        <DEVICE NAME="Cisco Micro Webserver 200" MDFID="268437679"
                                CISCOMDFID="268437679">
                                <SYSOID OID="1.3.6.1.4.1.9.1.176" NAME="OID:1.3.6.1.4.1.9.1.176" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco 4600 Series Content Distribution Manager"
                        MDFID="268437641" CISCOMDFID="268437641">
                        <DEVICE NAME="Cisco 4650 Content Distribution Manager" MDFID="268437642"
                                CISCOMDFID="268437642">
                                <SYSOID OID="1.3.6.1.4.1.9.1.487" NAME="OID:1.3.6.1.4.1.9.1.487" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 4630 Content Distribution Manager" MDFID="268437643"
                                CISCOMDFID="268437643">
                                <SYSOID OID="1.3.6.1.4.1.9.1.486" NAME="OID:1.3.6.1.4.1.9.1.486" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco 500 Series Content Engines"
                        MDFID="268437657" CISCOMDFID="268437657">
                        <DEVICE NAME="Cisco 507 Content Engine" MDFID="268437658"
                                CISCOMDFID="268437658">
                                <SYSOID OID="1.3.6.1.4.1.9.1.409" NAME="OID:1.3.6.1.4.1.9.1.409" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 507 AV Content Engine" MDFID="268437659"
                                CISCOMDFID="268437659">
                                <SYSOID OID="1.3.6.1.4.1.9.1.432" NAME="OID:1.3.6.1.4.1.9.1.432" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 560 Content Engine" MDFID="268437660"
                                CISCOMDFID="268437660">
                                <SYSOID OID="1.3.6.1.4.1.9.1.410" NAME="OID:1.3.6.1.4.1.9.1.410" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.433" NAME="OID:1.3.6.1.4.1.9.1.433" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 590 Content Engine" MDFID="268437661"
                                CISCOMDFID="268437661">
                                <SYSOID OID="1.3.6.1.4.1.9.1.411" NAME="OID:1.3.6.1.4.1.9.1.411" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 510 Content Engine" MDFID="277991115"
                                CISCOMDFID="277991115">
                                <SYSOID OID="1.3.6.1.4.1.9.1.505" NAME="OID:1.3.6.1.4.1.9.1.505" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 565 Content Engine" MDFID="277991121"
                                CISCOMDFID="277991121">
                                <SYSOID OID="1.3.6.1.4.1.9.1.491" NAME="OID:1.3.6.1.4.1.9.1.491" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 566 Content Engine" MDFID="279362873"
                                CISCOMDFID="279362873">
                                <SYSOID OID="1.3.6.1.4.1.9.1.596" NAME="OID:1.3.6.1.4.1.9.1.596" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco 600 Series Content Engines"
                        MDFID="999990970" CISCOMDFID="999990970">
                        <DEVICE NAME="Cisco 611 Content Engine" MDFID="999990971"
                                CISCOMDFID="999990971">
                                <SYSOID OID="1.3.6.1.4.1.9.1.708" NAME="OID:1.3.6.1.4.1.9.1.708" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 674 Content Engine" MDFID="999990978"
                                CISCOMDFID="999990978">
                                <SYSOID OID="1.3.6.1.4.1.9.1.996" NAME="OID:1.3.6.1.4.1.9.1.996" />
                        </DEVICE>
                </DEVICEGROUP>-->
                <DEVICEGROUP NAME="Cisco Wide Area Application Engine (WAE) Appliances"
                        MDFID="280000350" CISCOMDFID="280000350">
                        <!-- <DEVICE NAME="Cisco WAE-274 Wide Area Application Engine"
                                MDFID="280658976" CISCOMDFID="280658976">
                                <SYSOID OID="1.3.6.1.4.1.9.1.987" NAME="OID:1.3.6.1.4.1.9.1.987" />
                        </DEVICE>
                        <DEVICE NAME="Cisco WAE-474 Wide Area Application Engine"
                                MDFID="280658977" CISCOMDFID="280658977">
                                <SYSOID OID="1.3.6.1.4.1.9.1.986" NAME="OID:1.3.6.1.4.1.9.1.986" />
                        </DEVICE>
                        <DEVICE NAME="Cisco WAE-511 Wide Area Application Engines"
                                MDFID="280214396" CISCOMDFID="280214396">
                                <SYSOID OID="1.3.6.1.4.1.9.1.595" NAME="OID:1.3.6.1.4.1.9.1.595" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.681" NAME="OID:1.3.6.1.4.1.9.1.681" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.785" NAME="OID:1.3.6.1.4.1.9.1.785" />
                        </DEVICE> -->
                        <DEVICE NAME="Cisco WAE-512 Wide Area Application Engine"
                                MDFID="280658978" CISCOMDFID="280658978">
                                <SYSOID OID="1.3.6.1.4.1.9.1.759" NAME="OID:1.3.6.1.4.1.9.1.759" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.776" NAME="OID:1.3.6.1.4.1.9.1.776" />
                        </DEVICE>
                        <!-- <DEVICE NAME="Cisco WAE-574 Wide Area Application Engine"
                                MDFID="280658979" CISCOMDFID="280658979">
                                <SYSOID OID="1.3.6.1.4.1.9.1.985" NAME="OID:1.3.6.1.4.1.9.1.985" />
                        </DEVICE>
                        <DEVICE NAME="Cisco WAE-611 Wide Area Application Engine"
                                MDFID="280000622" CISCOMDFID="280000622">
                                <SYSOID OID="1.3.6.1.4.1.9.1.786" NAME="OID:1.3.6.1.4.1.9.1.786" />
                        </DEVICE> -->
                        <DEVICE NAME="Cisco WAE-612 Wide Area Application Engine"
                                MDFID="280449934" CISCOMDFID="280449934">
                                <SYSOID OID="1.3.6.1.4.1.9.1.757" NAME="OID:1.3.6.1.4.1.9.1.757" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.761" NAME="OID:1.3.6.1.4.1.9.1.761" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.777" NAME="OID:1.3.6.1.4.1.9.1.777" />
                        </DEVICE>
                        <DEVICE NAME="Cisco WAE-674 Wide Area Application Engine"
                                MDFID="999990988" CISCOMDFID="999990988">
                                <SYSOID OID="1.3.6.1.4.1.9.1.957" NAME="OID:1.3.6.1.4.1.9.1.957" />
                        </DEVICE>
                        <!-- <DEVICE NAME="Cisco WAE-7326 Wide Area Application Engine"
                                MDFID="280000375" CISCOMDFID="280000375">
                                <SYSOID OID="1.3.6.1.4.1.9.1.787" NAME="OID:1.3.6.1.4.1.9.1.787" />
                        </DEVICE> -->
                        <DEVICE NAME="Cisco WAE-7341 Wide Area Application Engine"
                                MDFID="999990986" CISCOMDFID="999990986">
                                <SYSOID OID="1.3.6.1.4.1.9.1.907" NAME="OID:1.3.6.1.4.1.9.1.907" />
                        </DEVICE>
                        <DEVICE NAME="Cisco WAE-7371 Wide Area Application Engine"
                                MDFID="999990985" CISCOMDFID="999990985">
                                <SYSOID OID="1.3.6.1.4.1.9.1.908" NAME="OID:1.3.6.1.4.1.9.1.908" />
                        </DEVICE>
                </DEVICEGROUP>
                <!-- <DEVICEGROUP NAME="Cisco 7300 Series Content Engines"
                        MDFID="268437662" CISCOMDFID="268437662">
                        <DEVICE NAME="Cisco 7320 Content Engine" MDFID="268437663"
                                CISCOMDFID="268437663">
                                <SYSOID OID="1.3.6.1.4.1.9.1.412" NAME="OID:1.3.6.1.4.1.9.1.412" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 7305 Content Engine" MDFID="277991123"
                                CISCOMDFID="277991123">
                                <SYSOID OID="1.3.6.1.4.1.9.1.504" NAME="OID:1.3.6.1.4.1.9.1.504" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 7325 Content Engine" MDFID="277991137"
                                CISCOMDFID="277991137">
                                <SYSOID OID="1.3.6.1.4.1.9.1.492" NAME="OID:1.3.6.1.4.1.9.1.492" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 7306 Content Engine" MDFID="279362912"
                                CISCOMDFID="279362912">
                                <SYSOID OID="1.3.6.1.4.1.9.1.600" NAME="OID:1.3.6.1.4.1.9.1.600" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 7326 Content Engine" MDFID="279362884"
                                CISCOMDFID="279362884">
                                <SYSOID OID="1.3.6.1.4.1.9.1.601" NAME="OID:1.3.6.1.4.1.9.1.601" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 7341 Content Engine" MDFID="999990979"
                                CISCOMDFID="999990979">
                                <SYSOID OID="1.3.6.1.4.1.9.1.982" NAME="OID:1.3.6.1.4.1.9.1.982" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 7371 Content Engine" MDFID="999990980"
                                CISCOMDFID="999990980">
                                <SYSOID OID="1.3.6.1.4.1.9.1.983" NAME="OID:1.3.6.1.4.1.9.1.983" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco DistributedDirector" MDFID="268437667"
                        CISCOMDFID="268437667" ICON="16x16_Distributed_Director_SF.gif">
                        <DEVICE NAME="Cisco DistributedDirector 4700M" MDFID="268437670"
                                CISCOMDFID="268437670">
                                <SYSOID OID="1.3.6.1.4.1.9.1.50" NAME="OID:1.3.6.1.4.1.9.1.50" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco CSS 11000 Series Content Services Switches"
                        MDFID="268437673" CISCOMDFID="268437673">
                        <DEVICE NAME="Cisco CSS 11050 Content Services Switch" MDFID="269065642"
                                CISCOMDFID="269065642">
                                <SYSOID OID="1.3.6.1.4.1.2467.4.4" NAME="OID:1.3.6.1.4.1.2467.4.4" />
                        </DEVICE>
                        <DEVICE NAME="Cisco CSS 11100 Content Services Switch" MDFID="999990319"
                                CISCOMDFID="999990319">
                                <SYSOID OID="1.3.6.1.4.1.2467.4.1" NAME="OID:1.3.6.1.4.1.2467.4.1" />
                        </DEVICE>
                        <DEVICE NAME="Cisco CSS 11150 Content Services Switch" MDFID="269065643"
                                CISCOMDFID="269065643">
                                <SYSOID OID="1.3.6.1.4.1.2467.4.3" NAME="OID:1.3.6.1.4.1.2467.4.3" />
                        </DEVICE>
                        <DEVICE NAME="Cisco CSS 11800 Content Services Switch" MDFID="269065644"
                                CISCOMDFID="269065644">
                                <SYSOID OID="1.3.6.1.4.1.2467.4.2" NAME="OID:1.3.6.1.4.1.2467.4.2" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco 4400 Series Content Routers"
                        MDFID="269065641" CISCOMDFID="269065641">
                        <DEVICE NAME="Cisco 4450 Content Router" MDFID="268437666"
                                CISCOMDFID="268437666">
                                <SYSOID OID="1.3.6.1.4.1.9.1.532" NAME="OID:1.3.6.1.4.1.9.1.532" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 4430 Content Router" MDFID="270570994"
                                CISCOMDFID="270570994">
                                <SYSOID OID="1.3.6.1.4.1.9.1.531" NAME="OID:1.3.6.1.4.1.9.1.531" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco CSS 11500 Series Content Services Switches"
                        MDFID="274011463" CISCOMDFID="274011463">
                        <DEVICE NAME="Cisco CSS 11506 Content Services Switch" MDFID="274011470"
                                CISCOMDFID="274011470">
                                <SYSOID OID="1.3.6.1.4.1.2467.4.6" NAME="OID:1.3.6.1.4.1.2467.4.6" />
                                <SYSOID OID="1.3.6.1.4.1.9.9.368.4.6" NAME="OID:1.3.6.1.4.1.9.9.368.4.6" />
                        </DEVICE>
                        <DEVICE NAME="Cisco CSS 11503 Content Services Switch" MDFID="274011473"
                                CISCOMDFID="274011473">
                                <SYSOID OID="1.3.6.1.4.1.2467.4.5" NAME="OID:1.3.6.1.4.1.2467.4.5" />
                                <SYSOID OID="1.3.6.1.4.1.9.9.368.4.5" NAME="OID:1.3.6.1.4.1.9.9.368.4.5" />
                        </DEVICE>
                        <DEVICE NAME="Cisco CSS 11501 Content Services Switch" MDFID="277880154"
                                CISCOMDFID="277880154">
                                <SYSOID OID="1.3.6.1.4.1.2467.4.7" NAME="OID:1.3.6.1.4.1.2467.4.7" />
                                <SYSOID OID="1.3.6.1.4.1.9.9.368.4.7" NAME="OID:1.3.6.1.4.1.9.9.368.4.7" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP
                        NAME="Cisco ACE GSS 4400 Series Global Site Selector Appliances"
                        MDFID="277122759" CISCOMDFID="277122759">
                        <DEVICE NAME="Cisco GSS 4480,4490,4491,4492R Global Site Selector"
                                MDFID="277122823" CISCOMDFID="277122823">
                                <SYSOID OID="1.3.6.1.4.1.9.1.517" NAME="OID:1.3.6.1.4.1.9.1.517" />
                        </DEVICE>
                        <DEVICE NAME="Cisco GSS 4490 Global Site Selector" MDFID="278489691"
                                CISCOMDFID="278489691">
                                <SYSOID OID="1.3.6.1.4.1.9.1.518" NAME="OID:1.3.6.1.4.1.9.1.518" />
                        </DEVICE>
                        <DEVICE NAME="Cisco GSS 4491 Global Site Selector" MDFID="279692888"
                                CISCOMDFID="279692888">
                                <SYSOID OID="1.3.6.1.4.1.9.1.519" NAME="OID:1.3.6.1.4.1.9.1.519" />
                        </DEVICE>
                </DEVICEGROUP>
        </DEVICEGROUP>
        <DEVICEGROUP NAME="DSL and Long Reach Ethernet (LRE)"
                MDFID="268437860" CISCOMDFID="268437860" ICON="16x16_LRE_StandbyCommand_SF.gif">
                <DEVICEGROUP NAME="DSL" MDFID="278875264" CISCOMDFID="278875264">
                        <DEVICE NAME="Cisco 6200 Series IP DSL Switches" MDFID="268438115"
                                CISCOMDFID="268438115">
                                <SYSOID OID="1.3.6.1.4.1.9.1.192" NAME="OID:1.3.6.1.4.1.9.1.192" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco 600 Series Modems" MDFID="268437861"
                        CISCOMDFID="268437861">
                        <DEVICE NAME="Cisco 626 ADSL Modem" MDFID="268437863"
                                CISCOMDFID="268437863">
                                <SYSOID OID="1.3.6.1.4.1.9.1.329" NAME="OID:1.3.6.1.4.1.9.1.329" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 627 ADSL Modem" MDFID="268437864"
                                CISCOMDFID="268437864">
                                <SYSOID OID="1.3.6.1.4.1.9.1.330" NAME="OID:1.3.6.1.4.1.9.1.330" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 633 SDSL Digital Service Unit" MDFID="268437865"
                                CISCOMDFID="268437865">
                                <SYSOID OID="1.3.6.1.4.1.9.1.331" NAME="OID:1.3.6.1.4.1.9.1.331" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco Catalyst 2900 Series LRE XL Switches"
                        MDFID="268438055" CISCOMDFID="268438055">
                        <DEVICE NAME="Cisco Catalyst 2912 LRE XL Switch" MDFID="268438056"
                                CISCOMDFID="268438056">
                                <SYSOID OID="1.3.6.1.4.1.9.1.370" NAME="OID:1.3.6.1.4.1.9.1.370" />
                        </DEVICE>
                        <DEVICE NAME="Cisco Catalyst 2924 LRE XL Switch" MDFID="268438057"
                                CISCOMDFID="268438057">
                                <SYSOID OID="1.3.6.1.4.1.9.1.369" NAME="OID:1.3.6.1.4.1.9.1.369" />
                        </DEVICE>
                        <DEVICE NAME="Cisco Catalyst 2908 XL Switch" MDFID="999990233"
                                CISCOMDFID="999990233">
                                <SYSOID OID="1.3.6.1.4.1.9.1.170" NAME="OID:1.3.6.1.4.1.9.1.170" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco 6000 Series IP DSL Switches"
                        MDFID="268438108" CISCOMDFID="268438108">
                        <DEVICE NAME="Cisco 6015 IP DSL Switch" MDFID="268438109"
                                CISCOMDFID="268438109">
                                <SYSOID OID="1.3.6.1.4.1.9.1.299" NAME="OID:1.3.6.1.4.1.9.1.299" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 6130 IP DSL Switch" MDFID="268438113"
                                CISCOMDFID="268438113">
                                <SYSOID OID="1.3.6.1.4.1.9.1.252" NAME="OID:1.3.6.1.4.1.9.1.252" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 6160 IP DSL Switch" MDFID="268438114"
                                CISCOMDFID="268438114">
                                <SYSOID OID="1.3.6.1.4.1.9.1.297" NAME="OID:1.3.6.1.4.1.9.1.297" />
                        </DEVICE>
                        <DEVICE NAME="Cisco 6260 IP DSL Switch" MDFID="268438116"
                                CISCOMDFID="268438116">
                                <SYSOID OID="1.3.6.1.4.1.9.1.253" NAME="OID:1.3.6.1.4.1.9.1.253" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco Catalyst 2950 LRE Series Switches"
                        MDFID="277869492" CISCOMDFID="277869492">
                        <DEVICE NAME="Cisco Catalyst 2950 8 LRE Switch" MDFID="277822412"
                                CISCOMDFID="277822412">
                                <SYSOID OID="1.3.6.1.4.1.9.1.483" NAME="OID:1.3.6.1.4.1.9.1.483" />
                        </DEVICE>
                        <DEVICE NAME="Cisco Catalyst 2950 24 LRE Switch" MDFID="277822424"
                                CISCOMDFID="277822424">
                                <SYSOID OID="1.3.6.1.4.1.9.1.482" NAME="OID:1.3.6.1.4.1.9.1.482" />
                        </DEVICE>
                </DEVICEGROUP>
        </DEVICEGROUP>
        <DEVICEGROUP NAME="Optical Networking" MDFID="268437868"
                CISCOMDFID="268437868" ICON="16x16-Optical_blue_sf.gif">
                <DEVICEGROUP NAME="Metro Core" MDFID="278875299"
                        CISCOMDFID="278875299">
                        <DEVICE NAME="Cisco Metro 1500 Series (MAN DWDM)" MDFID="268437874"
                                CISCOMDFID="268437874">
                                <SYSOID OID="1.3.6.1.4.1.2544.1.3" NAME="OID:1.3.6.1.4.1.2544.1.3" />
                        </DEVICE>
                        <DEVICE NAME="Cisco ONS 15454" MDFID="274259310" CISCOMDFID="274259310">
                                <SYSOID OID="1.3.6.1.4.1.3607.1.20.10.10" NAME="OID:1.3.6.1.4.1.3607.1.20.10.10" />
                        </DEVICE>
                </DEVICEGROUP>
                <DEVICEGROUP NAME="Cisco ONS 15500 Series" MDFID="268437889"
                        CISCOMDFID="268437889">
                        <DEVICE NAME="Cisco ONS 15540 ESP Extended Services Platform"
                                MDFID="273612892" CISCOMDFID="273612892">
                                <SYSOID OID="1.3.6.1.4.1.9.1.406" NAME="OID:1.3.6.1.4.1.9.1.406" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.481" NAME="OID:1.3.6.1.4.1.9.1.481" />
                        </DEVICE>
                        <DEVICE NAME="Cisco ONS 15530 DWDM Multiservice Aggregation Platform"
                                MDFID="276852950" CISCOMDFID="276852950">
                                <SYSOID OID="1.3.6.1.4.1.9.1.460" NAME="OID:1.3.6.1.4.1.9.1.460" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.461" NAME="OID:1.3.6.1.4.1.9.1.461" />
                                <SYSOID OID="1.3.6.1.4.1.9.1.462" NAME="OID:1.3.6.1.4.1.9.1.462" />
                        </DEVICE>